version: '2'
services:
  node:
    image: 'node:12'
    user: 'node'
    ports:
      - 8081:8081
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    # expose:
    #   - '8081'
    command: 'yarn;npm start'

    asia.gcr.io/silken-agent-289708/